# Délimitation X et y

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
import numpy as np
from sklearn.model_selection import learning_curve
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from scipy import stats
from sklearn.linear_model import Ridge, Lasso, LinearRegression
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.model_selection import cross_val_score
import math
from tensorflow.keras import Sequential
from sklearn.linear_model import ElasticNetCV
from update_checker import update_check
from tpot.builtins import CombineDFs, StackingEstimator
from xgboost import XGBRegressor
from sklearn.linear_model import SGDRegressor

2021-12-03 16:50:23.962836: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-12-03 16:50:23.962877: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/etienne/.pyenv/versions/3.8.12/envs/steamator/lib/python3.8/site-packages/tpot/builtins/__init__.py:36: UserWarning: Warning: optional dependency `torch` is not available. - skipping import of NN models.
  warnings.warn("Warning: optional dependency `torch` is not available. - skipping import of NN models.")

In [2]:
data = pd.read_csv("../raw_data/data_final_indé_small.csv")

In [3]:
data_price = data[data['price'] > 2 ]

In [4]:
data_price

,steam_appid,name,top_5_tags,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,...,english,price,has_a_website,nb_review,owner_estimated,rating,popularity,score_descriptif,average_playtime,median_playtime
0,4290,RACE: Caterham Expansion,racing simulation relaxing realistic real_time...,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,...,1,3.99,1,6,1248.0,424.233333,517.758333,4,0,0
2,7340,Azada,casual puzzle 1980s relaxing realistic,0.015666,0.307211,0.015666,0.015666,0.015666,0.015666,0.015666,...,1,6.99,1,12,2496.0,7.012399,9.197810,1,0,0
3,9960,Haunted House™,adventure 1980s relaxing realistic real_time_w...,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,...,1,4.79,1,22,4576.0,215.087500,263.378125,3,0,0
4,9970,Star Raiders,action space 1980s realistic real_time_with_pause,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,...,1,6.99,1,29,6032.0,209.787500,263.028125,2,0,0
5,10140,3D Ultra™ Minigolf Adventures,sports mini_golf golf local_multiplayer science,0.015755,0.015755,0.136535,0.015755,0.015755,0.015755,0.015755,...,1,6.99,0,78,16224.0,1253.642857,1824.928571,6,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18523,1065160,Deatherem,horror first_person survival_horror real_time_...,0.467192,0.015716,0.015716,0.015716,0.015716,0.015716,0.015716,...,1,2.09,0,4,832.0,5.450000,8.993750,6,0,0
18524,1065230,Room of Pandora,adventure casual puzzle 1980s relaxing,0.015694,0.701810,0.015694,0.015694,0.015694,0.015694,0.015694,...,1,2.09,0,3,624.0,3.000000,3.000000,1,0,0
18526,1065650,Super Star Blast,action casual 1980s relaxing realistic,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,...,1,3.99,1,1,208.0,4.600000,10.450000,5,0,0
18527,1066700,New Yankee 7: Deer Hunters,casual adventure 1980s relaxing realistic,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,...,1,5.19,1,2,416.0,23.463964,29.301802,2,0,0
18528,1069460,Rune Lord,casual adventure 1980s relaxing realistic,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,...,1,5.19,1,4,832.0,21.097297,26.485135,3,0,0

In [5]:
obj = data.isnull().sum()
for key,value in obj.iteritems():
    print(f'"{key}"')

"steam_appid"
"name"
"top_5_tags"
"topic_0"
"topic_1"
"topic_2"
"topic_3"
"topic_4"
"topic_5"
"topic_6"
"topic_7"
"topic_8"
"topic_9"
"topic_10"
"topic_11"
"topic_12"
"topic_13"
"topic_14"
"topic_15"
"topic_16"
"topic_17"
"topic_18"
"topic_19"
"english"
"price"
"has_a_website"
"nb_review"
"owner_estimated"
"rating"
"popularity"
"score_descriptif"
"average_playtime"
"median_playtime"

In [6]:
X = data_price.drop(columns=["steam_appid",
                        "name",
                       "top_5_tags",
                       "nb_review",
                       "owner_estimated",
                       "topic_7",
                       "rating",
                       "popularity",
                      "average_playtime",
                    "median_playtime"])
#X = data[['name']]
y = data_price['owner_estimated']

In [7]:
X.columns

Index(['topic_0', 'topic_1', 'topic_2', 'topic_3', 'topic_4', 'topic_5',
       'topic_6', 'topic_8', 'topic_9', 'topic_10', 'topic_11', 'topic_12',
       'topic_13', 'topic_14', 'topic_15', 'topic_16', 'topic_17', 'topic_18',
       'topic_19', 'english', 'price', 'has_a_website', 'score_descriptif'],
      dtype='object')

In [8]:
y

0         1248.0
2         2496.0
3         4576.0
4         6032.0
5        16224.0
          ...
18523      832.0
18524      624.0
18526      208.0
18527      416.0
18528      832.0
Name: owner_estimated, Length: 13045, dtype: float64

In [9]:
X

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_8,topic_9,topic_10,...,topic_14,topic_15,topic_16,topic_17,topic_18,topic_19,english,price,has_a_website,score_descriptif
0,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,...,0.015822,0.015822,0.428065,0.015822,0.015822,0.015822,1,3.99,1,4
2,0.015666,0.307211,0.015666,0.015666,0.015666,0.015666,0.015666,0.015666,0.015666,0.015666,...,0.015666,0.015666,0.015666,0.015666,0.015666,0.410797,1,6.99,1,1
3,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,...,0.015546,0.015546,0.015546,0.015546,0.015546,0.704628,1,4.79,1,3
4,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,...,0.016158,0.275846,0.016158,0.016158,0.016158,0.433305,1,6.99,1,2
5,0.015755,0.015755,0.136535,0.015755,0.015755,0.015755,0.015755,0.267618,0.154468,0.015755,...,0.015755,0.015755,0.015755,0.015755,0.189293,0.015755,1,6.99,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18523,0.467192,0.015716,0.015716,0.015716,0.015716,0.015716,0.015716,0.249924,0.015716,0.015716,...,0.015716,0.015716,0.015716,0.015716,0.015716,0.015716,1,2.09,0,6
18524,0.015694,0.701810,0.015694,0.015694,0.015694,0.015694,0.015694,0.015694,0.015694,0.015694,...,0.015694,0.015694,0.015694,0.015694,0.015694,0.015694,1,2.09,0,1
18526,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,...,0.015483,0.015483,0.015483,0.015483,0.015483,0.705831,1,3.99,1,5
18527,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,...,0.015466,0.015466,0.015466,0.015466,0.015466,0.706139,1,5.19,1,2
18528,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,...,0.015466,0.015466,0.015466,0.015466,0.015466,0.706139,1,5.19,1,3

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Baseline model

In [11]:
resultat = 0
for i in y:
    score = (10000-i)**2
    resultat += score
print(resultat/len(y))
print(math.sqrt(resultat/len(y)))

56652137.46140283
7526.761419189719

# Scaler

In [12]:
scaler = StandardScaler()
scaler.fit(X_train)
scaler.transform(X_train)
scaler.transform(X_test)

array([[-0.2956824 , -0.23393904, -0.24653899, ..., -0.07223752,
         0.66914607,  3.63633625],
       [-0.30142509, -0.24234929, -0.25376632, ..., -0.75245449,
        -1.49444202,  0.96489154],
       [ 2.2141203 , -0.24091513, -0.25253388, ..., -0.75245449,
        -1.49444202, -1.32491821],
       ...,
       [-0.30102516, -0.24176359, -0.253263  , ...,  1.03832079,
         0.66914607,  0.20162162],
       [-0.3015282 , -0.2425003 , -0.25389609, ...,  0.48304163,
        -1.49444202,  0.96489154],
       [-0.30236771,  1.8343255 , -0.25495264, ..., -0.37764106,
         0.66914607, -0.94328325]])

In [13]:
from sklearn.linear_model import Ridge, Lasso, LinearRegression

linreg = LinearRegression().fit(X_train, y_train)
ridge = Ridge(alpha=0.2).fit(X_train, y_train)
lasso = Lasso(alpha=0.2).fit(X_train, y_train)

coefs = pd.DataFrame({
    "coef_linreg": pd.Series(linreg.coef_, index = X.columns),
    "coef_ridge": pd.Series(ridge.coef_, index = X.columns),
    "coef_lasso": pd.Series(lasso.coef_, index= X.columns)})\

coefs\
    .applymap(lambda x: int(x))\
    .style.applymap(lambda x: 'color: red' if x == 0 else 'color: black')

# Model

In [14]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, StackingRegressor
from sklearn.linear_model import Lasso, LinearRegression
from catboost import CatBoostRegressor

forest = RandomForestRegressor(n_estimators=100, max_leaf_nodes=1000, max_depth=50)
KNN = KNeighborsRegressor(n_neighbors=10)
lasso = Lasso(max_iter=5000,positive=True, fit_intercept=False, )
GBR = GradientBoostingRegressor(
    n_estimators=100, 
    learning_rate=0.1,
    max_depth=3)
SGD = SGDRegressor(max_iter=1000, tol=1e-3)
    
ensemble = StackingRegressor(
    estimators = [('GBR', GBR), ("lasso", lasso), ('forest', forest)],
    final_estimator = GBR,
                n_jobs=-1)

In [15]:
model  = RandomForestRegressor(
                               bootstrap=True,
                               max_features=0.4,
                               min_samples_leaf=14,
                               n_estimators=100,
                               min_samples_split=14)

In [16]:
# Add Estimator
pipe = make_pipeline(ensemble)

# Train pipeline
pipe.fit(X_train,y_train)

# Make predictions
#pipe.predict(X_test.iloc[0:2])

# Cross validate pipeline
cross_val_score(ensemble, X_test, y_test, cv=5, scoring='r2').mean()
#cross_val_score(ensemble, X_test, y_test, cv=5, scoring='r2').mean()

0.2128679773177991

In [17]:
math.sqrt(32835810)

5730.2539210754