# Ouverture data

In [22]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
import numpy as np
from sklearn.model_selection import learning_curve
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from scipy import stats
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer, make_column_selector
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [23]:
data = pd.read_csv('../raw_data/data_final_indé_small.csv')

In [24]:
data

,steam_appid,name,top_5_tags,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,...,english,price,has_a_website,nb_review,owner_estimated,rating,popularity,score_descriptif,average_playtime,median_playtime
0,4290,RACE: Caterham Expansion,racing simulation relaxing realistic real_time...,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,...,1,3.99,1,6,1248.0,424.233333,517.758333,4,0,0
1,4900,Zen of Sudoku,casual puzzle 1980s relaxing realistic,0.015666,0.307211,0.015666,0.015666,0.015666,0.015666,0.015666,...,1,0.00,1,139,20000.0,22124.365000,23631.392500,3,0,0
2,7340,Azada,casual puzzle 1980s relaxing realistic,0.015666,0.307211,0.015666,0.015666,0.015666,0.015666,0.015666,...,1,6.99,1,12,2496.0,7.012399,9.197810,1,0,0
3,9960,Haunted House™,adventure 1980s relaxing realistic real_time_w...,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,...,1,4.79,1,22,4576.0,215.087500,263.378125,3,0,0
4,9970,Star Raiders,action space 1980s realistic real_time_with_pause,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,...,1,6.99,1,29,6032.0,209.787500,263.028125,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18524,1065230,Room of Pandora,adventure casual puzzle 1980s relaxing,0.015694,0.701810,0.015694,0.015694,0.015694,0.015694,0.015694,...,1,2.09,0,3,624.0,3.000000,3.000000,1,0,0
18525,1065570,Cyber Gun,action adventure fps 3d_platformer fast_paced,0.016478,0.016478,0.519926,0.016478,0.183470,0.016478,0.016478,...,1,1.69,0,9,1872.0,13.366667,16.816667,3,0,0
18526,1065650,Super Star Blast,action casual 1980s relaxing realistic,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,...,1,3.99,1,1,208.0,4.600000,10.450000,5,0,0
18527,1066700,New Yankee 7: Deer Hunters,casual adventure 1980s relaxing realistic,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,...,1,5.19,1,2,416.0,23.463964,29.301802,2,0,0
18528,1069460,Rune Lord,casual adventure 1980s relaxing realistic,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,...,1,5.19,1,4,832.0,21.097297,26.485135,3,0,0

# Def X et y

In [25]:
X = data.drop(columns=['steam_appid','name', 'top_5_tags', 'nb_review', 'owner_estimated', 'rating', 'popularity', 'average_playtime', 'median_playtime'])
y = data.owner_estimated

In [26]:
X

,topic_0,topic_1,topic_2,topic_3,topic_4,topic_5,topic_6,topic_7,topic_8,topic_9,...,topic_14,topic_15,topic_16,topic_17,topic_18,topic_19,english,price,has_a_website,score_descriptif
0,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,0.015822,...,0.015822,0.015822,0.428065,0.015822,0.015822,0.015822,1,3.99,1,4
1,0.015666,0.307211,0.015666,0.015666,0.015666,0.015666,0.015666,0.015666,0.015666,0.015666,...,0.015666,0.015666,0.015666,0.015666,0.015666,0.410797,1,0.00,1,3
2,0.015666,0.307211,0.015666,0.015666,0.015666,0.015666,0.015666,0.015666,0.015666,0.015666,...,0.015666,0.015666,0.015666,0.015666,0.015666,0.410797,1,6.99,1,1
3,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,0.015546,...,0.015546,0.015546,0.015546,0.015546,0.015546,0.704628,1,4.79,1,3
4,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,0.016158,...,0.016158,0.275846,0.016158,0.016158,0.016158,0.433305,1,6.99,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18524,0.015694,0.701810,0.015694,0.015694,0.015694,0.015694,0.015694,0.015694,0.015694,0.015694,...,0.015694,0.015694,0.015694,0.015694,0.015694,0.015694,1,2.09,0,1
18525,0.016478,0.016478,0.519926,0.016478,0.183470,0.016478,0.016478,0.016478,0.016478,0.016478,...,0.016478,0.016478,0.016478,0.016478,0.016478,0.016478,1,1.69,0,3
18526,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,0.015483,...,0.015483,0.015483,0.015483,0.015483,0.015483,0.705831,1,3.99,1,5
18527,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,...,0.015466,0.015466,0.015466,0.015466,0.015466,0.706139,1,5.19,1,2
18528,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,0.015466,...,0.015466,0.015466,0.015466,0.015466,0.015466,0.706139,1,5.19,1,3

In [27]:
y

0         1248.0
1        20000.0
2         2496.0
3         4576.0
4         6032.0
          ...
18524      624.0
18525     1872.0
18526      208.0
18527      416.0
18528      832.0
Name: owner_estimated, Length: 18529, dtype: float64

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Def model